# taken from
# https://code.visualstudio.com/api/working-with-extensions/continuous-integration
# just initial setup
# subject to changes
name: ESlint

on: push

jobs:
  run-linters:
    name: Run ESlint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # ESLint must be in `package.json`
      - name: Install Node.js dependencies
        run: npm install

      - name: set ESlint permissions
        run: chmod 0555 ./node_modules/.bin/eslint 
        
      - name: run ESlint
        run: ./node_modules/.bin/eslint ./extension/JavaScript/*.js

